# стр. 116
# try-except
"""""""""
try:        # ако в try  блока възникне грешка, неговото изпълнение се прекратява, което става причина за грешка
            # и командите разположени след него не се изпълняват
    pass
except:     # тоз блок се изпълнява само и единствено когато в try блока има възникнала грешка
            
            # 
    pass
""""""""""""
print("Обработка на изключения")
try:         # контролируем код
    num = int(input("въведете цяло число"))
    print("Виевъведохте числто :", num)
except:
    print("Грешни входни данни. Въведете цяло число")
print("Благодаря за съдействието!")
"""""""""""""""



